throw "Can't use BWL.Models without BWL module loaded" unless BWL?

BWL.Models = {} unless BWL.Models?

BWL.Models.AccessRequest = 
  Type: 'AccessRequest'
  _perms: null
  _rels: null
  CanRespond: false
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  Key: null
  RequestedAccess: null
  RequestedBy: null
  RequestedByKey: null
  RequestedByName: null
  RequestedItem: null
  RequestSentToKeys: null
  Response: null
  ResponseFrom: null
  ResponseFromKey: null
  StoreKey: null

BWL.Models.AccountProfile = 
  Type: 'AccountProfile'
  _perms: null
  _rels: null
  Active: false
  DateCreated: null
  DateModified: null
  DomainProfile: null
  Email: null
  EmailVerified: false
  FirstName: null
  FullName: null
  IsMarkedRemove: false
  Key: null
  LastName: null
  PasswordHash: null
  RequestedRole: null
  StoreKey: null

BWL.Models.Address = 
  Type: 'Address'
  _perms: null
  _rels: null
  AddressLine1: null
  AddressLine2: null
  AddressType: null
  City: null
  Country: null
  County: null
  DateCreated: null
  DateModified: null
  District: null
  IsConfirmed: false
  IsMarkedRemove: false
  Key: null
  Latitude: 0
  Longitude: 0
  PostalCode: null
  Region: null
  StoreKey: null
  Timezone: null

BWL.Models.AuthAccessToken = 
  Type: 'AuthAccessToken'
  _perms: null
  _rels: null
  ClientIP: null
  ClientKey: null
  DateCreated: null
  DateModified: null
  DisplayType: null
  IsMarkedRemove: false
  Key: null
  ProviderId: null
  ProviderType: null
  SessionKey: null
  State: null
  StoreKey: null

BWL.Models.AuthProfile = 
  Type: 'AuthProfile'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  DateOfBirth: null
  DomainProfile: null
  EmailAddress: null
  FirstName: null
  FullName: null
  Gender: null
  IsMarkedRemove: false
  Key: null
  LastName: null
  ProviderAccessSecret: null
  ProviderAccessToken: null
  ProviderId: null
  ProviderType: null
  ProviderVerified: false
  PublicImageURL: null
  PublicProfileURL: null
  StoreKey: null

BWL.Models.AuthSession = 
  Type: 'AuthSession'
  _perms: null
  _rels: null
  ClientIP: null
  ClientKey: null
  DateCreated: null
  DateModified: null
  DisplayType: null
  IsMarkedRemove: false
  Key: null
  ProviderAccessSecret: null
  ProviderAccessToken: null
  ProviderAccessVerifier: null
  ProviderId: null
  ProviderRequestSecret: null
  ProviderRequestToken: null
  ProviderType: null
  RedirectURL: null
  SessionType: null
  State: null
  StoreKey: null

BWL.Models.Cart = 
  Type: 'Cart'
  _perms: null
  _rels: null
  Currency: null
  DateCreated: null
  DateModified: null
  ExpiryDateTime: null
  Fees: null
  InventoryItems: null
  IsMarkedRemove: false
  Key: null
  Order: null
  Payment: null
  ProfileKey: null
  RequiresShipping: false
  Shipping: null
  ShippingAddress: null
  State: null
  StoreKey: null
  SubTotal: null
  Taxes: null
  Total: null

BWL.Models.Category = 
  Type: 'Category'
  _perms: null
  _rels: null
  ChildCategories: null
  CustomURI: null
  DateCreated: null
  DateModified: null
  Description: null
  DisplayOrder: 0
  Image: null
  IsMarkedRemove: false
  Key: null
  Name: null
  ParentCategoryKey: null
  RankingScore: 0
  SmallImage: null
  StoreKey: null

BWL.Models.City = 
  Type: 'City'
  _perms: null
  _rels: null
  CountryISO: null
  DateCreated: null
  DateModified: null
  geonameId: null
  IsMarkedRemove: false
  Key: null
  Latitude: 0
  Longitude: 0
  Name: null
  NameUpper: null
  NameUTF8: null
  Population: 0
  Region: null
  RegionCode: null
  RegionISO: null
  StoreKey: null
  Timezone: null
  TimezoneName: null

BWL.Models.Contact = 
  Type: 'Contact'
  _perms: null
  _rels: null
  Addresses: null
  Age: 0
  AlternativePhone: null
  CompanyName: null
  ContactRole: null
  DateCreated: null
  DateModified: null
  DateOfBirth: null
  EmailAddress: null
  Facsimile: null
  FirstName: null
  FullName: null
  Gender: null
  Image: null
  IsMarkedRemove: false
  Key: null
  LastName: null
  Phone: null
  PreferredName: null
  PrimaryAddress: null
  StoreKey: null
  WebAddress: null

BWL.Models.ContainerConfiguration = 
  Type: 'ContainerConfiguration'
  _perms: null
  _rels: null
  ConfigurationKey: null
  DateCreated: null
  DateModified: null
  Host: null
  IsMarkedRemove: false
  Key: null
  StoreKey: null
  Value: null

BWL.Models.Continent = 
  Type: 'Continent'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  geonameId: null
  IsMarkedRemove: false
  ISO: null
  Key: null
  Name: null
  StoreKey: null

BWL.Models.Copyright = 
  Type: 'Copyright'
  _perms: null
  _rels: null
  Contacts: null
  DateCreated: null
  DateModified: null
  HolderName: null
  IsMarkedRemove: false
  Key: null
  StoreKey: null

BWL.Models.Country = 
  Type: 'Country'
  _perms: null
  _rels: null
  AreaSqKM: 0
  Capital: null
  ContinentISO: null
  CurrencyCode: null
  CurrencyName: null
  DateCreated: null
  DateModified: null
  Fips: null
  geonameId: null
  HasCities: false
  HasPostalCodes: false
  HasRegions: false
  IsMarkedRemove: false
  ISO: null
  ISO3: null
  ISONumeric: null
  Key: null
  Languages: null
  Name: null
  Neighbours: null
  Phone: null
  Population: 0
  PostalCodeFormat: null
  PostalCodeRegex: null
  StoreKey: null
  TLD: null

BWL.Models.Currency = 
  Type: 'Currency'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  DecimalPlaces: 0
  DecimalSeparator: null
  HTMLCharacter: null
  IsMarkedRemove: false
  ISO: null
  Key: null
  Name: null
  PrefixCharacter: false
  StoreKey: null
  ThousandsSeparator: null
  ToUSDConversionRate: 0
  UnicodeCharacter: null

BWL.Models.CustomURI = 
  Type: 'CustomURI'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  Key: null
  StoreKey: null
  URI: null

BWL.Models.DigitalSource = 
  Type: 'DigitalSource'
  _perms: null
  _rels: null
  BaseURL: null
  Copyright: null
  DateCreated: null
  DateModified: null
  Description: null
  Filename: null
  FileSize: 0
  IsMarkedRemove: false
  Key: null
  MimeInfo: null
  Name: null
  SourceFile: null
  StoreKey: null

BWL.Models.DomainProfile = 
  Type: 'DomainProfile'
  _perms: null
  _rels: null
  AccessToken: null
  AuthProfiles: null
  Contact: null
  DateCreated: null
  DateModified: null
  DomainProfileId: 0
  IsMarkedRemove: false
  Key: null
  LastLogoff: null
  LastLogon: null
  ProfileRole: null
  StoreKey: null

BWL.Models.Event = 
  Type: 'Event'
  _perms: null
  _rels: null
  Categories: null
  ChildEvents: null
  Contacts: null
  CustomURI: null
  DateCreated: null
  DateModified: null
  Description: null
  DisplayOrder: 0
  EndTime: null
  IsMarkedRemove: false
  Items: null
  Key: null
  LargeImages: null
  MaximumCapacity: 0
  Name: null
  OnSaleDateTimeEnd: null
  OnSaleDateTimeStart: null
  ParentEvent: null
  Places: null
  Public: false
  RankingScore: 0
  SearchPriority: 0
  SmallImage: null
  StartTime: null
  StoreKey: null
  WebLinks: null

BWL.Models.ExternalInfo = 
  Type: 'ExternalInfo'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  Description: null
  IsMarkedRemove: false
  Key: null
  Name: null
  ProviderId: null
  StoreKey: null

BWL.Models.Facebook = 
  Type: 'Facebook'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  Description: null
  FacebookType: null
  IsMarkedRemove: false
  Key: null
  Name: null
  ProviderId: null
  StoreKey: null

BWL.Models.Fee = 
  Type: 'Fee'
  _perms: null
  _rels: null
  Amount: 0
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  Key: null
  Name: null
  StoreKey: null

BWL.Models.File = 
  Type: 'File'
  _perms: null
  _rels: null
  BaseURL: null
  Copyright: null
  DateCreated: null
  DateModified: null
  Description: null
  Filename: null
  FileSize: 0
  IsMarkedRemove: false
  Key: null
  MimeInfo: null
  Name: null
  SourceFile: null
  StoreKey: null

BWL.Models.Flickr = 
  Type: 'Flickr'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  Description: null
  IsMarkedRemove: false
  Key: null
  Name: null
  ProviderId: null
  StoreKey: null

BWL.Models.GeneralAdmissionTicketInventoryItem = 
  Type: 'GeneralAdmissionTicketInventoryItem'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  DownloadLink: null
  EventKey: null
  EventName: null
  Info: null
  InventoryItemInfoKey: null
  InventoryItemInfoType: null
  IsLocked: false
  IsMarkedRemove: false
  IsSold: false
  ItemInfoKey: null
  ItemInfoName: null
  ItemInfoPrice: null
  ItemInfoType: null
  Key: null
  LockExpiryDateTime: null
  LockingDomainProfileKey: null
  Options: null
  ScanDateTime: null
  ScanDeviceKey: null
  SoldDateTime: null
  SoldToDomainProfileKey: null
  StoreKey: null
  UIID: 0

BWL.Models.GeneralAdmissionTicketItemInfo = 
  Type: 'GeneralAdmissionTicketItemInfo'
  _perms: null
  _rels: null
  Categories: null
  CustomURI: null
  DateCreated: null
  DateModified: null
  Description: null
  DisplayOrder: 0
  EventKey: null
  EventName: null
  InventoryKey: null
  IsMarkedRemove: false
  IsTaxable: false
  Items: null
  Key: null
  LargeImages: null
  MaxPurchaseQuantity: 0
  Name: null
  NumberAvailable: 0
  NumberTotal: 0
  OnSaleDateTimeEnd: null
  OnSaleDateTimeStart: null
  Options: null
  ParentItem: null
  Policy: null
  PreviewImages: null
  Price: null
  PricingParent: null
  PricingTiers: null
  Public: false
  RankingScore: 0
  SalePrice: null
  SalePriority: 0
  SearchPriority: 0
  ShowCountdown: false
  SmallImage: null
  StoreKey: null
  TaxRules: null
  TicketTemplate: null
  Unlimited: false

BWL.Models.Image = 
  Type: 'Image'
  _perms: null
  _rels: null
  BaseURL: null
  Copyright: null
  DateCreated: null
  DateModified: null
  Description: null
  DPI: 0
  Filename: null
  FileSize: 0
  HeightPX: 0
  ImageFile: null
  IsMarkedRemove: false
  Key: null
  MimeInfo: null
  Name: null
  SourceFile: null
  StoreKey: null
  ThumbFile: null
  WidthPX: 0

BWL.Models.InventoryItem = 
  Type: 'InventoryItem'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  EventKey: null
  EventName: null
  InventoryItemInfoKey: null
  InventoryItemInfoType: null
  IsLocked: false
  IsMarkedRemove: false
  IsSold: false
  ItemInfoKey: null
  ItemInfoName: null
  ItemInfoPrice: null
  ItemInfoType: null
  Key: null
  LockExpiryDateTime: null
  LockingDomainProfileKey: null
  Options: null
  SoldDateTime: null
  SoldToDomainProfileKey: null
  StoreKey: null
  UIID: 0

BWL.Models.ItemInfo = 
  Type: 'ItemInfo'
  _perms: null
  _rels: null
  Categories: null
  CustomURI: null
  DateCreated: null
  DateModified: null
  Description: null
  DisplayOrder: 0
  EventKey: null
  EventName: null
  InventoryKey: null
  IsMarkedRemove: false
  IsTaxable: false
  Items: null
  Key: null
  LargeImages: null
  MaxPurchaseQuantity: 0
  Name: null
  NumberAvailable: 0
  NumberTotal: 0
  OnSaleDateTimeEnd: null
  OnSaleDateTimeStart: null
  Options: null
  ParentItem: null
  PreviewImages: null
  Price: null
  PricingParent: null
  PricingTiers: null
  Public: false
  RankingScore: 0
  SalePrice: null
  SalePriority: 0
  SearchPriority: 0
  ShowCountdown: false
  SmallImage: null
  StoreKey: null
  TaxRules: null
  Unlimited: false

BWL.Models.ItemOptionRequest = 
  Type: 'ItemOptionRequest'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  DisplayOrder: 0
  IsMarkedRemove: false
  Key: null
  OptionType: null
  Price: null
  Required: false
  StoreKey: null
  Text: null
  Value: null

BWL.Models.ItemOptionResponse = 
  Type: 'ItemOptionResponse'
  Key: null
  OptionType: null
  Price: null
  Text: null
  Value: null

BWL.Models.LastFM = 
  Type: 'LastFM'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  Description: null
  IsMarkedRemove: false
  Key: null
  LastFMType: null
  Name: null
  ProviderId: null
  StoreKey: null

BWL.Models.LinkedIn = 
  Type: 'LinkedIn'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  Description: null
  IsMarkedRemove: false
  Key: null
  LinkedInType: null
  Name: null
  ProviderId: null
  StoreKey: null

BWL.Models.MySpace = 
  Type: 'MySpace'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  Description: null
  IsMarkedRemove: false
  Key: null
  Name: null
  ProviderId: null
  StoreKey: null

BWL.Models.Order = 
  Type: 'Order'
  _perms: null
  _rels: null
  Contact: null
  Currency: null
  DateCreated: null
  DateModified: null
  DomainProfileKey: null
  Fees: null
  Fulfilled: null
  InventoryItems: null
  IsMarkedRemove: false
  Key: null
  OrderId: 0
  Placed: null
  RequiresShipping: false
  Shipped: null
  Shipping: null
  ShippingAddress: null
  State: null
  StoreKey: null
  SubTotal: null
  Taxes: null
  Total: null
  Transactions: null

BWL.Models.PaymentProvider = 
  Type: 'PaymentProvider'
  _perms: null
  _rels: null
  Currency: null
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  Key: null
  MaximumCharge: null
  MinimumCharge: null
  OnApprovedOrderState: null
  Policy: null
  ProviderId: null
  ProviderToken: null
  ProviderType: null
  StoreKey: null

BWL.Models.PaymentSession = 
  Type: 'PaymentSession'
  _perms: null
  _rels: null
  Amount: null
  AuthToken: null
  CartKey: null
  ClientIP: null
  DateCreated: null
  DateModified: null
  DisplayType: null
  IsMarkedRemove: false
  Key: null
  Message: null
  PaymentSessionId: 0
  ProfileKey: null
  ProviderReceipt: null
  ProviderType: null
  RedirectURL: null
  State: null
  StoreKey: null

BWL.Models.Place = 
  Type: 'Place'
  _perms: null
  _rels: null
  Address: null
  Contacts: null
  CustomURI: null
  DateCreated: null
  DateModified: null
  Description: null
  DisplayOrder: 0
  IsMarkedRemove: false
  Key: null
  LargeImages: null
  Name: null
  Public: false
  RankingScore: 0
  SearchPriority: 0
  SmallImage: null
  StoreKey: null

BWL.Models.PostalCode = 
  Type: 'PostalCode'
  _perms: null
  _rels: null
  CityName: null
  Code: null
  CountryISO: null
  County: null
  DateCreated: null
  DateModified: null
  District: null
  IsMarkedRemove: false
  Key: null
  Latitude: 0
  Longitude: 0
  Region: null
  RegionISO: null
  StoreKey: null

BWL.Models.Price = 
  Type: 'Price'
  Currency: null
  Display: null
  ItemPrice: 0

BWL.Models.Region = 
  Type: 'Region'
  _perms: null
  _rels: null
  Code: null
  Country: null
  CountryISO: null
  DateCreated: null
  DateModified: null
  geonameId: null
  IsMarkedRemove: false
  ISO: null
  Key: null
  Name: null
  StoreKey: null

BWL.Models.RegionSet = 
  Type: 'RegionSet'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  Key: null
  Name: null
  Regions: null
  StoreKey: null

BWL.Models.RegistrationInventoryItem = 
  Type: 'RegistrationInventoryItem'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  EventKey: null
  EventName: null
  InventoryItemInfoKey: null
  InventoryItemInfoType: null
  IsLocked: false
  IsMarkedRemove: false
  IsSold: false
  ItemInfoKey: null
  ItemInfoName: null
  ItemInfoPrice: null
  ItemInfoType: null
  Key: null
  LockExpiryDateTime: null
  LockingDomainProfileKey: null
  Options: null
  SoldDateTime: null
  SoldToDomainProfileKey: null
  StoreKey: null
  UIID: 0

BWL.Models.RegistrationItemInfo = 
  Type: 'RegistrationItemInfo'
  _perms: null
  _rels: null
  Categories: null
  CustomURI: null
  DateCreated: null
  DateModified: null
  Description: null
  DisplayOrder: 0
  EventKey: null
  EventName: null
  InventoryKey: null
  IsMarkedRemove: false
  IsTaxable: false
  Items: null
  Key: null
  LargeImages: null
  MaxPurchaseQuantity: 0
  Name: null
  NumberAvailable: 0
  NumberTotal: 0
  OnSaleDateTimeEnd: null
  OnSaleDateTimeStart: null
  Options: null
  ParentItem: null
  PreviewImages: null
  Price: null
  PricingParent: null
  PricingTiers: null
  Public: false
  RankingScore: 0
  SalePrice: null
  SalePriority: 0
  SearchPriority: 0
  ShowCountdown: false
  SmallImage: null
  StoreKey: null
  TaxRules: null
  Unlimited: false

BWL.Models.ScanDevice = 
  Type: 'ScanDevice'
  _perms: null
  _rels: null
  Active: false
  DateCreated: null
  DateModified: null
  Description: null
  DeviceInfo: null
  Events: null
  IsMarkedRemove: false
  Key: null
  LastSyncDateTime: null
  Name: null
  StoreKey: null

BWL.Models.ScanEventInfo = 
  Type: 'ScanEventInfo'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  EventDateTime: null
  IsMarkedRemove: false
  Key: null
  Name: null
  PlaceName: null
  StoreKey: null

BWL.Models.ScanTicket = 
  Type: 'ScanTicket'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  Info: null
  IsMarkedRemove: false
  Key: null
  ScanDateTime: null
  ScanDeviceKey: null
  StoreKey: null
  SyncDateModified: null
  TicketInfoKey: null
  Valid: false
  ValidationHash: null

BWL.Models.ScanTicketInfo = 
  Type: 'ScanTicketInfo'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  Key: null
  Name: null
  StoreKey: null

BWL.Models.SearchIndex = 
  Type: 'SearchIndex'
  _perms: null
  _rels: null
  Categories: null
  DateCreated: null
  DateModified: null
  Description: null
  IsMarkedRemove: false
  IsSalePrice: false
  ItemDateModified: null
  ItemKey: null
  ItemType: null
  Key: null
  Locations: null
  Name: null
  Price: null
  SearchPriority: 0
  SearchTags: null
  SearchText: null
  StoreKey: null
  URI: null

BWL.Models.SponsorshipInventoryItem = 
  Type: 'SponsorshipInventoryItem'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  EventKey: null
  EventName: null
  InventoryItemInfoKey: null
  InventoryItemInfoType: null
  IsLocked: false
  IsMarkedRemove: false
  IsSold: false
  ItemInfoKey: null
  ItemInfoName: null
  ItemInfoPrice: null
  ItemInfoType: null
  Key: null
  LockExpiryDateTime: null
  LockingDomainProfileKey: null
  Options: null
  SoldDateTime: null
  SoldToDomainProfileKey: null
  StoreKey: null
  UIID: 0

BWL.Models.SponsorshipItemInfo = 
  Type: 'SponsorshipItemInfo'
  _perms: null
  _rels: null
  Categories: null
  CustomURI: null
  DateCreated: null
  DateModified: null
  Description: null
  DisplayOrder: 0
  EventKey: null
  EventName: null
  InventoryKey: null
  IsMarkedRemove: false
  IsTaxable: false
  Items: null
  Key: null
  LargeImages: null
  MaxPurchaseQuantity: 0
  Name: null
  NumberAvailable: 0
  NumberTotal: 0
  OnSaleDateTimeEnd: null
  OnSaleDateTimeStart: null
  Options: null
  ParentItem: null
  PreviewImages: null
  Price: null
  PricingParent: null
  PricingTiers: null
  Public: false
  RankingScore: 0
  SalePrice: null
  SalePriority: 0
  SearchPriority: 0
  ShowCountdown: false
  SmallImage: null
  StoreKey: null
  TaxRules: null
  Unlimited: false

BWL.Models.Store = 
  Type: 'Store'
  _perms: null
  _rels: null
  Address: null
  Categories: null
  Contacts: null
  Currency: null
  DateCreated: null
  DateModified: null
  Description: null
  Events: null
  ExternalInfos: null
  HasAccounts: false
  HasWishlist: false
  IsMarkedRemove: false
  IsOwner: false
  Items: null
  Key: null
  LargeBannerImages: null
  LargeImages: null
  Name: null
  PaymentProviders: null
  Public: false
  SearchPriority: 0
  SmallBannerImage: null
  SmallImage: null
  StoreKey: null
  StoreURIs: null
  TaxRules: null
  WebLinks: null

BWL.Models.StoreConfiguration = 
  Type: 'StoreConfiguration'
  _perms: null
  _rels: null
  ConfigurationKey: null
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  Key: null
  StoreKey: null
  Value: null

BWL.Models.StorePreRegister = 
  Type: 'StorePreRegister'
  _perms: null
  _rels: null
  AddressLine1: null
  AddressLine2: null
  City: null
  ContactName: null
  Country: null
  County: null
  DateCreated: null
  DateModified: null
  District: null
  EmailAddress: null
  Facebook: null
  IsMarkedRemove: false
  Key: null
  Latitude: 0
  LinkedIn: null
  Longitude: 0
  Name: null
  Phone: null
  PostalCode: null
  Region: null
  StoreKey: null
  StoreURI: null
  Timezone: null
  Twitter: null
  WebAddress: null

BWL.Models.StoreURI = 
  Type: 'StoreURI'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  Key: null
  StoreKey: null
  URI: null

BWL.Models.Tax = 
  Type: 'Tax'
  _perms: null
  _rels: null
  Code: null
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  IsTaxonTax: false
  Key: null
  Name: null
  Number: null
  Percent: 0
  StoreKey: null

BWL.Models.TaxRule = 
  Type: 'TaxRule'
  _perms: null
  _rels: null
  CityKey: null
  CountryKey: null
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  Key: null
  RegionKey: null
  StoreKey: null
  Taxes: null

BWL.Models.TicketInventoryItem = 
  Type: 'TicketInventoryItem'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  DownloadLink: null
  EventKey: null
  EventName: null
  Info: null
  InventoryItemInfoKey: null
  InventoryItemInfoType: null
  IsLocked: false
  IsMarkedRemove: false
  IsSold: false
  ItemInfoKey: null
  ItemInfoName: null
  ItemInfoPrice: null
  ItemInfoType: null
  Key: null
  LockExpiryDateTime: null
  LockingDomainProfileKey: null
  Options: null
  ScanDateTime: null
  ScanDeviceKey: null
  SoldDateTime: null
  SoldToDomainProfileKey: null
  StoreKey: null
  UIID: 0

BWL.Models.TicketItemInfo = 
  Type: 'TicketItemInfo'
  _perms: null
  _rels: null
  Categories: null
  CustomURI: null
  DateCreated: null
  DateModified: null
  Description: null
  DisplayOrder: 0
  EventKey: null
  EventName: null
  InventoryKey: null
  IsMarkedRemove: false
  IsTaxable: false
  Items: null
  Key: null
  LargeImages: null
  MaxPurchaseQuantity: 0
  Name: null
  NumberAvailable: 0
  NumberTotal: 0
  OnSaleDateTimeEnd: null
  OnSaleDateTimeStart: null
  Options: null
  ParentItem: null
  Policy: null
  PreviewImages: null
  Price: null
  PricingParent: null
  PricingTiers: null
  Public: false
  RankingScore: 0
  SalePrice: null
  SalePriority: 0
  SearchPriority: 0
  ShowCountdown: false
  SmallImage: null
  StoreKey: null
  TaxRules: null
  TicketTemplate: null
  Unlimited: false

BWL.Models.TicketTemplate = 
  Type: 'TicketTemplate'
  _perms: null
  _rels: null
  BackgroundColorHex: null
  CustomTemplateImage: null
  DateCreated: null
  DateModified: null
  FontColorHex: null
  FontType: null
  Horizontal: false
  IncludeDetails: false
  IncludeQRCode: false
  IncludeSeatInfo: false
  IncludeTerms: false
  IncludeTicketImage: false
  IncludeTicketName: false
  IsMarkedRemove: false
  Key: null
  StoreKey: null
  Template: null

BWL.Models.Timezone = 
  Type: 'Timezone'
  _perms: null
  _rels: null
  CountryISO: null
  DateCreated: null
  DateModified: null
  DSTOffset: 0
  GMTOffset: 0
  IsMarkedRemove: false
  Key: null
  Name: null
  RawOffset: 0
  StoreKey: null

BWL.Models.Transaction = 
  Type: 'Transaction'
  _perms: null
  _rels: null
  Amount: null
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  Key: null
  Message: null
  ProviderReceipt: null
  ProviderType: null
  State: null
  StoreKey: null
  TransactionId: 0

BWL.Models.Twitter = 
  Type: 'Twitter'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  Description: null
  IsMarkedRemove: false
  Key: null
  Name: null
  ProviderId: null
  StoreKey: null

BWL.Models.WebLink = 
  Type: 'WebLink'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  Description: null
  IsMarkedRemove: false
  Key: null
  Name: null
  StoreKey: null
  URL: null

BWL.Models.Wishlist = 
  Type: 'Wishlist'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  IsMarkedRemove: false
  Items: null
  Key: null
  ProfileKey: null
  StoreKey: null

BWL.Models.YouTube = 
  Type: 'YouTube'
  _perms: null
  _rels: null
  DateCreated: null
  DateModified: null
  Description: null
  IsMarkedRemove: false
  Key: null
  Name: null
  ProviderId: null
  StoreKey: null